global using AirportSystem.Api.Application.Services;
global using AirportSystem.Api.Domain.Contracts.Repositories;
global using AirportSystem.Api.Domain.Contracts.Services;
global using AirportSystem.Api.Domain.Entities;
global using AirportSystem.Api.Infrastructure.Context;
global using AirportSystem.Api.Infrastructure.Repositories;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;